#Плагин создан Lymon_MineDel.
#LSRVVKPost - 1.1
#/fakepost - lsrvvkpost.fake - Отправить фейковый пост
#/latpost - lsrvvkpost.lat - Получить ссылку на последний пост
#Успешное получение ссылки на последний пост, будет если были сделаны посты после загрузки BungeeCord сервера!
vk-settings: #Данные от группы в ВК
  groupid: 123456 #ID группы
  groupToken: '1234567890abcd' #Токен группы
alert-newpost:
  - '&e&lНОВЫЙ ПОСТ В ГРУППЕ &b&lВК СЕРВЕРА'
  - '&d&lГруппа в &b&lВК&f: vk.com/lsrvtest'
  - '&a&lПост можно посмотреть написав команду&f: /latpost'
  - '&e&lНОВЫЙ ПОСТ В ГРУППЕ &b&lВК СЕРВЕРА'
lang: #Языковые настройки
  noperm: '&c&lУ вас нет прав!' #Сообщение если нету прав
  last-post: #Языковые настройки для последнего поста
    last: '&e&lСсылка на последний пост&f:' #Сообщение если есть последний пост, то даёт ссылку
    nolast: '&c&lНет недавних постов' #Сообщение если нету последних постов